# ec2 안에 들어가는 파일
version: '3'
services:

  web:
    container_name: web
    image: kyuwon0718/cmc-server
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/log:/log
#    environment:
#      - JASYPT_SECRET_KEY= jasypt key 넣기

  nginx:
    container_name: nginx
    image: kyuwon0718/nginx
    ports:
      - 80:80
    depends_on:
      - web
