# ec2 안에 들어가는 파일
version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt #letsencrypt폴더 위치
      - /var/log/nginx:/var/log/nginx # log파일의 위치
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      - TZ=Asia/Seoul

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt #letsencrypt폴더 위치
      - /var/log/nginx:/var/log/nginx # log파일의 위치
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  spring:
    container_name: spring
    image: kyuwon0718/cmc-server
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/log:/log
    environment:
      - TZ=Asia/Seoul
      #   - JASYPT_SECRET_KEY= your secret key here

#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redis/data:/data
#      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
#    restart: always
#    command: redis-server /usr/local/conf/redis.conf
#    environment:
#      - TZ=Asia/Seoul