# ec2 안에 들어가는 파일
version: '3'
services:

  web:
    container_name: web
    image: kyuwon0718/cmc-server
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/log:/log
    # environment:
    #   - JASYPT_SECRET_KEY= your secret key here
