version: '3'
services:

  web:
    container_name: web
    image: kyuwon0718/cmc-server
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: kyuwon0718/nginx
    ports:
      - 80:80
    depends_on:
      - web
