spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: update
        default_batch_fetch_size: 100
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(rHCYaZOVQI0V7YMtbofxRxBbgcrgI9xxMyJq1Sq+6b4DMdchnI65xvXjsi6mcwqfgXasDbrqIlDNjW6BtHKdc9Vj+YOOM+2mYwOhmL9Xc/plH6EUcB/leVsnFj5uOWOC/DH7a0I0XLw=)
    username: ENC(mchGcb/C+wJDKp1ReAr5dg==)
    password: ENCyWXUzKmvIIRNACbH4OAvLiQPKCxVTicl)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: ENC(+cYH8mP/Hfx82X+51RMtZm4vDwdGeMrBsfQGVuXk0DUmd5BRVfmHp9uC0NK31gt5dXU0VfVTIjieLCPRCUIKofslfgKhPz08+O/hK6OrxYg=)
  access-token-validity: 86400  # 60*60*24 : 1day
  refresh-token-validity: 7776000 # 60*60*24*90 : 3month

# multipart 설정
spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 10MB

# s3 설정
cloud:
  aws:
    s3:
      bucket: ENC(WtZKOIsxJeUwmxn9eLlLWYWj4dyYHDn1)
      iamAccessKey: ENC(3eAIRrUHGkx9xVF4XtBaaYdi+17r7/GT2wbRspDjOvo=)
      iamSecretKey: ENC(UXlxGMCXGbYug9dT4WkWHeqkRHXfY6KmFW13l95ZdpxvLe0XH/J9hNTL/Pf+fyT/NCKOvLIvcys=)
    region:
      static: ap-northeast-2

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


