spring:
  redis:
    host: localhost
    port: 3306
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: update
        default_batch_fetch_size: 100
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#     local
    url: jdbc:mysql://localhost:3306/cmc_database
    username: root
    password: root123!
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        usr_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: health,info,beans,conditions,heapdump,threaddump,metrics,prometheus