spring:
  profiles:
    group:
      "test": "test, common"
      "dev": "dev, common"
      "prod": "prod, common"

server:
  port: 8080

jwt:
  secret: ENC(+cYH8mP/Hfx82X+51RMtZm4vDwdGeMrBsfQGVuXk0DUmd5BRVfmHp9uC0NK31gt5dXU0VfVTIjieLCPRCUIKofslfgKhPz08+O/hK6OrxYg=)
  access-token-validity: 86400  # 60*60*24 : 1day
  refresh-token-validity: 7776000 # 60*60*24*90 : 3month

# multipart 설정
spring.servlet.multipart.max-file-size: 5MB
spring.servlet.multipart.max-request-size: 10MB

# s3 설정
cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ENC(WtZKOIsxJeUwmxn9eLlLWYWj4dyYHDn1)
      iamAccessKey: ENC(3eAIRrUHGkx9xVF4XtBaaYdi+17r7/GT2wbRspDjOvo=)
      iamSecretKey: ENC(UXlxGMCXGbYug9dT4WkWHeqkRHXfY6KmFW13l95ZdpxvLe0XH/J9hNTL/Pf+fyT/NCKOvLIvcys=)
    region:
      static: ap-northeast-2

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    secret-key: ${JASYPT_SECRET_KEY}

# swaggerdoc
springdoc:
  version: '@v1'
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# kakao
kakao:
  client-id: ENC(cA9sz9r0RidlWDIdD4shtbt9sdoSSjUX9hHifGkHbICWe7uPgq4Ydh45MFaubzds)
  redirect-uri: http://localhost:3000

# fcm
fcm:
  key:
    path: fcm-key.json
    scope: https://www.googleapis.com/auth/firebase.messageing
    api-url: ENC(gC2m2ivuWUPr13CEbDwOL9IkarbqdAqF3ffB146fwdixYDGsM6+toHiIPKG/1E42SzMW1TWdln+TK0hq9mP1wQoIWuHHulqnIvFuXIXQO9w=)