name: dev-spring-springboot

on:
  push:
    branches:
      - Fix/#50
#      - master

env:
  IMAGE_IAM_ACCESS_KEY: ${{ secrets.IMAGE_IAM_ACCESS_KEY }}
  IMAGE_IAM_SECRET_KEY: ${{ secrets.IMAGE_IAM_SECRET_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  LOCAL_DB_PASSWORD: ${{ secrets.LOCAL_DB_PASSWORD }}
  LOCAL_DB_USERNAME: ${{ secrets.LOCAL_DB_USERNAME }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_DATABASE: 'cmc_database'
#          MYSQL_ROOT
#          MYSQL_ROOT_PASSWORD: ${{ secrets.LOCAL_DB_PASSWORD }}
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'cmc_database'
          mysql user: 'root'
          mysql password: ${{ secrets.LOCAL_DB_PASSWORD }} # github Secret 탭에서 설정하세요!

      - name: Verify MySQL connection
        run: |
            mysql --version
            sudo apt-get install -y mysql-client
            mysql --host 127.0.0.1 --port 3306 -uroot -p${{ secrets.LOCAL_DB_PASSWORD }} -e "SHOW DATABASES"

#      - name: Setup MySQL
#        uses: samin/mysql-action@v1
#        with:
#          character set server: 'utf8'
#          mysql database: 'cmc_database'
#          mysql user: 'root'
#          mysql password: ${{ secrets.LOCAL_DB_PASSWORD }}
#
#      - name: verify MySQL connection from host
#        run: |
#            mysql --version

      - name: set environment variable
        run: |
          echo "IMAGE_IAM_ACCESS_KEY= ${{ secrets.IMAGE_IAM_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "IMAGE_IAM_SECRET_KEY= ${{ secrets.IMAGE_IAM_SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_SECRET= ${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "LOCAL_DB_PASSWORD= ${{ secrets.LOCAL_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "LOCAL_DB_USERNAME= ${{ secrets.LOCAL_DB_USERNAME }}" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME= ${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV

      - name : env check
        run: |
          echo env.LOCAL_DB_USERNAME : ${{ env.LOCAL_DB_USERNAME }}
          echo ${{env.LOCAL_DB_USERNAME}}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: build

      - name: Build with Gradle

        run: |
          ./gradlew clean build -i
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=$"
        shell: bash

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .
          

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: cmc-server
          environment_name: Cmcserver-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip