name: Java CI with Gradle

on:
  push:
    branches:
      - Feat/#165

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make fcm-key.json
        run: |
          echo "copy to test/resources"
          touch ./src/main/resources/fcm-key.json
          echo $FILE >> ./src/main/resources/fcm-key.json
          
          echo "confirm file in main"
          cd ./src/main/resources
          pwd
          ls -a

        shell: bash
        env:
          FILE: ${{ secrets.FCM_KEY }}

      ## gradlew 권한
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cmc-server -f dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/cmc-server

      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker rm -f $( docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nginx
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cmc-server
            docker-compose up -d
            docker image prune -f